const DEFAULT_LAYOUT = [
  { id: 'now_playing', panel: 'now_playing', title: 'now playing', x: 1040, y: 20,  w: 380, h: 160, z: 1, kind: 'normal' },
  { id: 'lyrics',      panel: 'lyrics',      title: 'lyrics',      x: 1040, y: 190, w: 380, h: 160, z: 1, kind: 'normal' },
  { id: 'status',      panel: 'status',      title: 'pc status',   x: 20,   y: 900, w: 220, h: 130, z: 1, kind: 'normal' },
  { id: 'socials',     panel: 'socials',     title: 'socials',     x: 20,   y: 780, w: 220, h: 70,  z: 1, kind: 'normal', opts: { social_lines: 'twitter: @vanillyn_net\ndiscord: @vanillyn' } },
  { id: 'message_bar', panel: 'message_bar', title: 'message',    x: 20,   y: 740, w: 220, h: 36,  z: 1, kind: 'normal', opts: { text_color: '#d8dee2', bg_color: '#0a0c0d', font_size: 13, font_family: 'monospace' } },
  { id: 'screen',      panel: 'screen',      title: 'screen',      x: 260,  y: 780, w: 400, h: 260, z: 0, kind: 'normal' },
  { id: 'key_panel',   panel: 'key_panel',  title: 'keys',        x: 260,  y: 620, w: 280, h: 120, z: 1, kind: 'normal', opts: { shape: 'round', size: 48, gap: 8, glow: true, active_color: '#7ef7c6', inactive_color: '#1f2731', text_color: '#f5f7fa', keys: [{ key: 'w', label: 'W', shape: 'round', color: '#7ef7c6' }, { key: 'a', label: 'A', shape: 'square', color: '#7ef7c6' }, { key: 's', label: 'S', shape: 'square', color: '#7ef7c6' }, { key: 'd', label: 'D', shape: 'square', color: '#7ef7c6' }, { key: 'space', label: 'SPACE', shape: 'pill', color: '#8be9fd' }] } },
  { id: 'chat',        panel: 'chat',        title: 'chat',        x: 20,   y: 20,  w: 380, h: 480, z: 1, kind: 'normal', opts: { text_color: '#d8dee2', bg_color: '', font_size: 13, font_family: 'monospace' } },
  { id: 'extra',       panel: 'extra',       title: 'extra',       x: 1040, y: 900, w: 380, h: 130, z: 1, kind: 'normal', opts: { text_color: '#d8dee2', bg_color: '', font_size: 13, font_family: 'monospace' } },
  { id: 'spacer_1',    panel: 'spacer',      title: 'log',         x: 20,   y: 520, w: 220, h: 240, z: 1, kind: 'normal', opts: { spacer_kind: 'bootlog' } },
  { id: 'alerts',      panel: 'alerts',      title: 'alert',       x: 530,  y: 40,  w: 420, h: 140, z: 500, kind: 'popup', visible: false },
  { id: 'redeem_player', panel: 'redeem_player', title: 'redeem',  x: 460,  y: 300, w: 520, h: 440, z: 500, kind: 'popup', visible: false },
  { id: 'pngtuber',    panel: 'pngtuber',    title: 'pngtuber',    x: 900,  y: 500, w: 400, h: 580, z: 999999, kind: 'topmost' },
  { id: 'words',       panel: 'words',       title: 'words',       x: 300,  y: 200, w: 600, h: 500, z: 800, kind: 'normal', opts: { wos_url: 'https://wos.gg/' } },
  { id: 'tts_transcript', panel: 'tts_transcript', title: 'tts', x: 20, y: 660, w: 220, h: 70, z: 1, kind: 'normal', opts: { text_color: '#d8dee2', bg_color: '', font_size: 13, font_family: 'monospace' } },
  { id: 'ad_warning',  panel: 'ad_warning',  title: 'ad break',    x: 530,  y: 40,  w: 420, h: 100, z: 700, kind: 'popup', visible: false, opts: { text_color: '#ffb238', bg_color: '#1a1409', font_size: 16 } },
  { id: 'canvas',      panel: 'canvas',      title: 'canvas',      x: 520,  y: 260, w: 400, h: 400, z: 600, kind: 'popup', visible: false, opts: { size: 100, bg_color: '#0a0c0d' } },
];
